// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4bqtOh-MIe-QxUAL_ndE6IiXTsCGoOns',
    appId: '1:127114578507:web:eccebe378bf04e9806dbce',
    messagingSenderId: '127114578507',
    projectId: 'taxiapp-76f94',
    authDomain: 'taxiapp-76f94.firebaseapp.com',
    storageBucket: 'taxiapp-76f94.firebasestorage.app',
    measurementId: 'G-Y155QNZ53X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJgu980zFVNOMvnXTKB3QOVL9zfoYyXC8',
    appId: '1:127114578507:android:9077be6cc2f8758d06dbce',
    messagingSenderId: '127114578507',
    projectId: 'taxiapp-76f94',
    storageBucket: 'taxiapp-76f94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV-nHrcWBTo599vf3l96JKuamUNsOxEXE',
    appId: '1:127114578507:ios:22b47cf6ee7c76b806dbce',
    messagingSenderId: '127114578507',
    projectId: 'taxiapp-76f94',
    storageBucket: 'taxiapp-76f94.firebasestorage.app',
    iosBundleId: 'com.example.taxiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV-nHrcWBTo599vf3l96JKuamUNsOxEXE',
    appId: '1:127114578507:ios:22b47cf6ee7c76b806dbce',
    messagingSenderId: '127114578507',
    projectId: 'taxiapp-76f94',
    storageBucket: 'taxiapp-76f94.firebasestorage.app',
    iosBundleId: 'com.example.taxiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4bqtOh-MIe-QxUAL_ndE6IiXTsCGoOns',
    appId: '1:127114578507:web:9d05d8036bdb42bb06dbce',
    messagingSenderId: '127114578507',
    projectId: 'taxiapp-76f94',
    authDomain: 'taxiapp-76f94.firebaseapp.com',
    storageBucket: 'taxiapp-76f94.firebasestorage.app',
    measurementId: 'G-1THFY0MNHF',
  );

}